### ISSUE TITLE
squareBracket porting todo list

### ISSUE THREAD

**Issue by PF94** [PF94/squaretracle#15]
# Functionality

Functionality that is on openSB but missing on squareTracle.

* [ ] Username colors
* [ ] Footer options
* [x] Accessibility sounds
* [ ] Statistics page
* [ ] Favourites (but actually implement it)
* [ ] Display names (for profiles)
* [ ] Localization?

# Migration scripts

Unlike the code for the “PokTube to openSB” and “PokTwo to openSB” migrations which were written on a seperate codebase borrowing database code from openSB. The “openSB to squareTracle” migration code will need to be on the squareTracle codebase to be able to use the squareTracle stuff.

* [ ] Account/channel migration
* [ ] Video information migration
* [ ] Dynamic files migration
* [ ] Comments migration
* [ ] Subscription migration(?)
* [ ] Ratings migration
